# vim: expandtab: 

version: '3.8'
services:
  amo-exp-db:
    image: mariadb:10.5.4-focal
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=my-username
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my-database
    volumes:
      - data-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  amo-exp-crawler:
    build: ./crawler
    restart: always
    depends_on:
      - amo-exp-db
    environment:
      - NODE_ADDR=http://localhost:26657
      - CHAIN_ID=my-chain-id
    volumes:
      - ./db/config.json:/db/config.json
      - tmp-volume:/var/tmp/

  amo-exp-api:
    build: ./server
    restart: always
    depends_on:
      - amo-exp-crawler 
    volumes:
      - ./db/config.json:/db/config.json
    ports:
      - "3000:3000"

  amo-exp-web:
    build: ./react
    restart: always
    depends_on:
      - amo-exp-api 
    ports:
      - "5000:5000"

networks:
  default:
    driver: bridge

volumes:
  data-volume:
  tmp-volume:
